name: Build and Deploy

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run jest
        run:
          export MONGO_URI="${{ secrets.MONGO_URI }}"
          export JWT_SECRET="${{ secrets.JWT_SECRET }}"
          npm test

        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Angular CLI
        run: cd frontend && npm install -g @angular/cli
      
      - name: Install dependencies
        run: cd frontend && npm install && npm install tailwindcss postcss autoprefixer

      - name: Install and build angular app
        run: cd frontend && ng build --output-path=../dist 
      
      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy the service
        run: export RAILWAY_TOKEN="${{ secrets.RAILWAY_TOKEN }}"
             railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}